###################################
# Cousul will be used to register service which other services and discover
etcd:
  image: bitnami/etcd
  environment:
    - ALLOW_NONE_AUTHENTICATION=yes
    - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
  ports:
    - "2379:2379"
    - "2380:2380"
##################################
# Message broker to interact with other systems
rabbit:
  image: rabbitmq:management
  hostname: rabbit
  ports:
    - "5672:5672"
    - "15672:15672"

###################################
# Micro web to view and query service from web dashboard
microweb:
  image: micro/micro
  command: web --address=0.0.0.0:8080
  ports:
    - "80:8080"
  environment:
    - MICRO_REGISTRY=etcd
    - MICRO_REGISTRY_ADDRESS=etcd:2379
    - MICRO_API_NAMESPACE=gomicro.api
  links:
    - etcd
    - service.helloworld

###################################
# Our basic Helloworld service
service.helloworld:
  build: .
  command: gin --immediate --path /go/src/github.com/rajdeol/go-micro-hello-world go run main.go
  ports:
    - "3000:3000"
    - "8081:8080"
  volumes:
    - .:/go/src/github.com/rajdeol/go-micro-hello-world
  environment:
    - MICRO_REGISTRY=etcd
    - MICRO_REGISTRY_ADDRESS=etcd:2379
    - MICRO_BROKER=rabbitmq
    - MICRO_BROKER_ADDRESS=amqp://guest:guest@rabbit:5672
  links:
    - etcd
    - rabbit
